### ISSUE TITLE
Configure Office network

### ISSUE THREAD

**Issue by Professor-Woody** [Professor-Woody/Networking_Security_Project#11]
**Tasks**
Configure routing to:
- [ ] See the web server
- [ ] See the DB server
- [ ] See the internet
