### ISSUE TITLE
Find Security Patches for Windows

### ISSUE THREAD

**Issue by Professor-Woody** [Professor-Woody/Networking_Security_Project#14]
**Tasks**
- [ ] Find Windows version in lab
- [ ] Find latest security updates for Windows
- [ ] Install security updates on all machines being used
