### ISSUE TITLE
Find Security Patches for Servers

### ISSUE THREAD

**Issue by Professor-Woody** [Professor-Woody/Networking_Security_Project#15]
**Tasks**
- [ ] Find out how to update all software on linux
- [ ] Update web server
- [ ] Update DB server
