### ISSUE TITLE
Configure Firewall on Router

### ISSUE THREAD

**Issue by Professor-Woody** [Professor-Woody/Networking_Security_Project#3]
**Tasks**
- [ ] Enable the firewall on the router
- [ ] By default all traffic from the internet should be blocked
- [ ] Allow Ports 80, 443 from the internet
- [ ] Set up port forwarding to the webserver to allow traffic through only to there
